export const questionData = [
  {
    key: 1,
    question: "Who is the father of the nation ?",
    //correctAnswerMarkUpdate,
    //attempt,
    options: {
      option1: "Mahatma Gandhi",
      option2: "Jawaharlal Nehru",
      option3: "Donald Trump",
      option4: "Barrack Obama",
    },
    answer: "Mahatma Gandhi",
  },
  {
    key: 2,
    question: "What color is are the leaves ?",
    //correctAnswerMarkUpdate,
    //attempt,
    options: {
      option1: "Blue",
      option2: "Red",
      option3: "Yellow",
      option4: "Green",
    },
    answer: "Green",
  },
  {
    key: 3,
    question: "Who is the father of the nation ?",
    //correctAnswerMarkUpdate,
    //attempt,
    options: {
      option1: "Mahatma Gandhi",
      option2: "Jawaharlal Nehru",
      option3: "Donald Trump",
      option4: "Barrack Obama",
    },
    answer: "Mahatma Gandhi",
  },
  {
    key: 4,
    question: "Who is the father of the nation ?",
    //correctAnswerMarkUpdate,
    //attempt,
    options: {
      option1: "Mahatma Gandhi",
      option2: "Jawaharlal Nehru",
      option3: "Donald Trump",
      option4: "Barrack Obama",
    },
    answer: "Mahatma Gandhi",
  },
  {
    key: 5,
    question: "Who is the father of the nation ?",
    //correctAnswerMarkUpdate,
    //attempt,
    options: {
      option1: "Mahatma Gandhi",
      option2: "Jawaharlal Nehru",
      option3: "Donald Trump",
      option4: "Barrack Obama",
    },
    answer: "Mahatma Gandhi",
  },
];
